### ISSUE TITLE
Modificar la home para que quede adecuamente en 3 columnas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-RiverosSalomon-Lessio#5]
![imagen](https://user-images.githubusercontent.com/8345007/117553004-4900cd80-b025-11eb-98c0-fba3771c787d.png)
Quizás sería bueno emplear un estilo de column-count: 3
o mejorar los estilos de alguna manera que se pueda visualizar adecuadamente, sin tener que hacer scroll a los costados

**Comment by MatiasLessio** [comment]
Ahi arregle poniendo columnas en todas las hojas
